### ISSUE TITLE
error when first running counsel-jq

### ISSUE THREAD

**Issue by iantor** [200ok-ch/counsel-jq#2]
windows 10,  emacs 26.3

just installed jq (from chocolatey) and counsel-jq

When in json buffer, M-x counsel-jq, immediately get following:

Error in post-command-hook (icomplete-post-command-hook): (wrong-number-of-arguments (1 . 1) 3)
Quit

Then get prompt for jq query.

**Comment by munen** [comment]
Hi @iantor 

Thank you for checking out `counsel-jq`!

I have no Windows machine to test (I'm running Debian Linux and MacOS), so I'd be happy if you can help debug this issue. Let's check some versions first: I've been running Emacs 26 and now Emacs 27.1 with `counsel-jq`, so that shouldn't be it. I'm running `jq` in the latest version `1.6-1`.

**Comment by iantor** [comment]
Hi Munen, I have emacs 26.3, and jq 1.6-1
I have some limited debugging experience with emacs, will see if I can get some more details on that error and let you know.

**Comment by munen** [comment]
Hi @iantor 

Perfect, thank you very much and good luck!

If you can't find the issue, I think the best I can offer is to have a screen sharing session with you to help with debugging.

**Comment by iantor** [comment]
On the track of the issue.  I believe it has something to do with icomplete-mode and possibly with some other settings to do with counsel.  Saw the same error in a different context.  Will try disabling those settings and see what happens.

**Comment by iantor** [comment]
problem is solved.  It was caused by (icomplete-mode 1) in init.el, which shouldn't have been there since I am using Ivy and Counsel etc.

**Comment by munen** [comment]
@iantor Great, thank you for checking it out and getting back on this issue^^

I could have caught this probably in your error message, but I wasn't aware of `icomplete-mode`. Sorry for that. Personally, I still use `ido` for some things, but Ivy for most. It's a little complicated to set up, but once done has served me well for years. If it helps, here's my setup: https://github.com/munen/emacs.d/#search--completion The rationale why I'm not using Ivy for everything is here: https://github.com/munen/emacs.d/#where-ivy-doesnt-work-well

All the best and enjoy using `counsel-jq` :pray:
