### ISSUE TITLE
`counsel-jq` doesn't always use the correct source buffer

### ISSUE THREAD

**Issue by gilbertw1** [200ok-ch/counsel-jq#3]
Hi, 

I've found that `counsel-jq` when invoked doesn't always use the buffer it was invoked from when evaluating it's queries. I've noticed in a number of cases it instead using a different buffer from the one it was invoked from. 

The specific use case that fails for me in `doom-emacs` is to open a new empty buffer (`evil-buffer-new`), paste in a json block, then execute `counsel-jq`. In this scenario `counsel-jq` will never use the newly created buffer, but instead whichever buffer was selected prior.

I'm not positive, but I believe this is likely the result of using workspace features (such as `persp-mode`) to curate and separate buffers into specific workspaces. In the case of more transient buffers, it seems that the `buffer-list` and `other-buffer` aren't always reliable to always get the last selected buffer.

**Comment by munen** [comment]
Thank you very much for checking out `counsel-jq` and adding a contribution! :pray: 

Sorry to hear you're having problems with the package. Personally, I can't reproduce the problem as an evil user, but I don't use persp-mode.

I've added a bigger comment with potential steps directly in the PR.
