### ISSUE TITLE
Setting buffer ```*jq-json*``` to JSON mode automatically

### ISSUE THREAD

**Issue by mcraveiro** [200ok-ch/counsel-jq#5]
Hi counsel-jq developers,

thanks very much for an amazing tool! I used to use jq-interactively [1] for this kind of work, but your mode appears to be much faster! I have one question though: is there a way to default the ```*jq-json*``` results buffer to JSON?

Many thanks

[1] https://github.com/ljos/jq-mode

**Comment by munen** [comment]
Hi @mcraveiro 

Thanks for checking out `counsel-jq`(;

> I have one question though: is there a way to default the *jq-json* results buffer to JSON?

By defaulting "defaulting to JSON", do you mean to switch the major mode to something like `json-mode`?

**Comment by mcraveiro** [comment]
Hi @munen,

yes apologies, should have been more clear, I do mean that precisely, to change the major mode to ```json-mode```.

Cheers

**Comment by munen** [comment]
No worries, I understand it now^^

I think, if we're going with third-party modes, different people will have different preferences for that - someone might want `json-mode`, another `js2-mode`, another `rjsx-mode`.

So, I propose we do:

- The buffer `*jq-json*` defaults to the built-in `js-js2-mode` for Emacs > 27.1. For older Emacsen, it defaults to the built-in `js-mode`. 
- The major mode of `*jq-json*` can also be customized to whatever the user wants, so you could configure it to `json-mode` for example.

What do you think? If you like it, would you want to implement it?

**Comment by mcraveiro** [comment]
It sounds great! Now, I have never submitted a patch for any elisp project before, but this seems simple enough and I guess we all have to start somewhere :-D lemme have a go, and then perhaps you can fix my mista^W^W^W guide me in the PR :-D thanks!

**Comment by munen** [comment]
Implemented in #6.
