### ISSUE TITLE
Gives wrong results with `ivy-occur`

### ISSUE THREAD

**Issue by Gleek** [200ok-ch/counsel-jq#7]
`ivy-occur` can be used to get the filtered results in a separate buffer. 
It is similar to the default action which opens up the result in `*jq-json*` buffer but instead uses an occur buffer. 

This can help in filtering multiple json objects and compare the filtered results without having subsequent runs replace the results of previous ones.

Running `ivy-occur` (`C-c C-o` by default I think) opens up the full json object instead of only displaying the filtered results.

I'm unsure of what might be causing this or if this is a bug upstream in ivy.

**Comment by munen** [comment]
Hi @Gleek 

Thanks for checking out `counsel-jq`!

Could you make a screencast showing what you're doing? I'm not a user of ivy-occur and don't understand how you compose it with counsel-jq from the description.

**Comment by Gleek** [comment]
Hello @munen,

Please see the screencast below. I first demo a sample run of ivy-occur on counsel-describe-variable function. 
Running ivy-occur after some filtering returns the filtered results in a buffer.
Next I run counsel jq on a json and filter to a limited result. Running ivy-occur now does not retain the results, but instead shows the original json as is.


https://user-images.githubusercontent.com/3756804/108360019-ad767280-7216-11eb-91b5-96e355433683.mp4

**Comment by munen** [comment]
Thank you for providing that screencast, I can see it now! :+1: 

I assume `ivy-occur` is a wrapper around `occur` and that there's state tracked somewhere inside of ivy. `counsel-jq` uses ivy and counsel for dynamically querying an external command (`jq`). If ivy does not implicitly track this state, I assume that it has to be tracked explicitly to be compatible with `ivy-occur` (or maybe less likely that it is a bug within ivy).

Are you interested in looking into this and creating a PR for it?

**Comment by Gleek** [comment]
I'll see if I can figure out something this weekend. 🙂

**Comment by munen** [comment]
Cool, looking forward to it^^
